### ISSUE TITLE
partialRootPaths 

### ISSUE THREAD

**Issue by Messa1** [t3brightside/personnel#1]
Hey. 

I just use you pluign version 2.0.2 with typo3 version 8.7.30 and i just try to overwrite the templates.

So i just add this to my ts.

`personnel.partialRootPaths = EXT:fileadmin/templates/website/assets/templates/Personnel/Partials/
`
I check twice the code, and i only add for a test a `<h1>` to the Card.html
and I also flush all cache.

And nothing changed has changed at the output.

Best Regards
Matthias

**Comment by t3brightside** [comment]
Hey,

you need to check your folder path first. 'EXT:'  is extension folder and shouldn't be there before fileadmin/

Cheers,

Tanel

**Comment by Messa1** [comment]
Ah oky, i tried that first.

`personnel.partialRootPaths = fileadmin/templates/assets/templates/Personnel/Partials/`

I checked twice with my path: fileadmin/templates/assets/templates/Personnel/Partials/

So i just change in the Card.html just a line to check if it works

```
<div class="person card">
	<h1>TEST</h1>
  <f:if condition="{data.tx_personnel_images} == 0">
```

I don't see any change.

Best Regars
Matthias

**Comment by t3brightside** [comment]
You can always try to override it in TS setup. It's a customisation issue and there's no support for that. Besides it's an old version that won't be changed no more anyway. I recommend upgrading to latest LTS and using the latest version of the extension.

**Comment by Messa1** [comment]
So i just update to Typo3 9.5.13 and Personnel  2.3.0, same behavior.

In my TS it got  `personnel.partialRootPaths = fileadmin/templates/webiste/assets/templates/Personnel/Partials/`

Here you see a quick view in to my ftp.
![Bildschirmfoto 2020-01-22 um 14 36 49](https://user-images.githubusercontent.com/3908658/72898567-a71c7b00-3d24-11ea-8576-2ad229a52cb2.png)

**Comment by t3brightside** [comment]
"personnel.partialRootPaths" constant has no known bugs and works fine in multiple live projects for me. Customisation support is available only commercially.
