### ISSUE TITLE
TYPO3 constantly throws error due to allow_url_fopen set to 0

### ISSUE THREAD

**Issue by dsg1-wolf** [t3brightside/personnel#12]
Heya there,

this one's less of an error report but a question to the powers that be.
Is there a decent and maintainable way to somehow make use of Personnel AND have aforementioned PHP parameter set to zero? The only way I can think of was to completely overwrite your PHP using cURL.

Thx in advance!

**Comment by t3brightside** [comment]
Hey @dsg1-wolf ! Thanks for the feedback. It's an issue needs to be dealt with at some point indeed... Sadly no time to get a crack on it right now. But I think TYPO3's ImageService could be a solution here.

**Comment by t3brightside** [comment]
@dsg1-wolf if you feel like giving it a try, it's changed in dev now.
https://github.com/t3brightside/personnel/commit/ef6d6ebb197ff8fa98b5b786f3745883e28fb09a
