### ISSUE TITLE
Image size Problem

### ISSUE THREAD

**Issue by GitCybers** [t3brightside/personnel#2]
Hello,

there is a problem with the size of images in the card view. If i use this code `personnel.cardImageWidth = 100` in the constants the image won`t be set to 100px. You can see the result on: [http://test.kgsfrankenforst.de/foerderverein.html](url)
Thanks, Sascha

**Comment by t3brightside** [comment]
Hey! Image size in your example site is exactly right. 100px default and 200px for retina screens.
Thou image width constant doesn't concern css or layouts anyhow.

**Comment by GitCybers** [comment]
My original size ist 1692x2444. The image should be much smaller. For example like a "thumnail". I thougt I could change the size with `personnel.cardImageWidth = 100`.
Is there no way to set the maximum hight of the card?

**Comment by t3brightside** [comment]
Image height can be set by a constant as well. Default templates are just examples to work with. Feel free to create your own templates. I'll close the topic as it's not bug related and there's no non-commercial support.
