### ISSUE TITLE
Multilingualism

### ISSUE THREAD

**Issue by Messa1** [t3brightside/personnel#4]
I have chosen a 2 language for the output of the contact person. Unfortunately, the frontend only gives me 2 Platzhalers and not the 2 selected people in German, everything works without problems.

Did I miss something somewhere?

![Bildschirmfoto 2020-09-28 um 08 30 50](https://user-images.githubusercontent.com/3908658/94398228-77e8c400-0165-11eb-8e9a-b619f4f75e7c.png)
![Bildschirmfoto 2020-09-28 um 08 31 24](https://user-images.githubusercontent.com/3908658/94398224-75866a00-0165-11eb-9337-9f600ac7f6de.png)
![Bildschirmfoto 2020-09-28 um 08 31 12](https://user-images.githubusercontent.com/3908658/94398226-761f0080-0165-11eb-97df-bf927c91faf1.png)

**Comment by t3brightside** [comment]
Hey,

if selecting persons manually, I think in translated page you should still select the records in original language, not the translations. Give that a try.

**Comment by Messa1** [comment]
Hey.

Yes that works. The problem was that the EN Id was in use but you need to set the original person.
