### ISSUE TITLE
Bootstrap v5 compatiblity

### ISSUE THREAD

**Issue by ProWebs** [t3brightside/personnel#5]
We installed your extension to our new typo project on LTS 11, but it looks like your "vcard" template is not compatible with bootstrap v5. 

It breaks our layout. We need to remove your float: left css to fix it. 
Maybe it will be possible to add a compatible bootstrap v5 vcard template to you extension in future?

**Comment by t3brightside** [comment]
Hey, thanks for the feedback...

It's unlikely to happen that it will ever get tested in any framework. It's easy to customise the templates and in most cases it's probably the scenario anyway.

**Comment by ProWebs** [comment]
Of course not in every framework, but bootstrap is the most used one, so this will be a good feature for future.
