### ISSUE TITLE
Warning: Undefined array key "tx_news_domain_model_news"

### ISSUE THREAD

**Issue by zenoussi** [t3brightside/personnel#9]
Hello,
since my update PHP 7.4 => 8.1 I get the above mentioned message during my composer update caused by:

"Script typo3cms database:updateschema '*.add,*.change' handling the typo3-cms-scripts event returned with error code 1
Script @typo3-cms-scripts was called via post-update-cmd".

I use the typo3_console by Helmut Hummel in version 7.1.6 with TYPO3 v11.5.27 and the following information in the composer.json:

"scripts": {
    "typo3-deployment-scripts": [
        "typo3cms cache:flush"
    ],
    "typo3-cms-scripts": [
        "typo3cms install:fixfolderstructure",
        "typo3cms language:update",
        "typo3cms database:updateschema '*.add,*.change'"
    ],
    "post-install-cmd": [
        "@typo3-cms-scripts"
    ],
    "post-update-cmd": [
        "@typo3-cms-scripts"
    ]
},

Thanks a lot
Ulli

**Comment by sschuett** [comment]
I seem to have the same problem with a slightly different error message.

After updating from t3brightside/personnel 3.4.1 => 3.8.2 the command `typo3cms database:updateschema --dry-run` results in the error message 

 ```
 [ Doctrine\DBAL\Schema\SchemaException ]
  There is no column with name 't3ver_oid' on table 'tx_news_domain_model_news'.
```
This occurs with PHP 7.4.33 and TYPO3 11.5.28

**Comment by doreinhardt** [comment]
@t3brightside Is there a reason why you are suggesting the usage of "georgringer/news" extension via the composer.json as described here:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/FileStructure/ComposerJson.html#suggest

This should prevent most if not all of the loading order problems described above.

**Comment by t3brightside** [comment]
The feature will be actually dropped all together in next release as it probably makes more sense to put it in a separate extension for who may need it. Besides no time to keep it up to date.

**Comment by t3brightside** [comment]
Feature is dropped with the latest release.
